include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    curly_braces_in_flow_control_structures: ignore
    no_leading_underscores_for_local_identifiers: ignore

  exclude:
    - third-party

formatter:
  page_width: 120
  trailing_commas: preserve
